// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kyve/pool/v1beta1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "kyve.pool.v1beta1";

/** Params defines the pool module parameters. */
export interface Params {
  /** protocol_inflation_share ... */
  protocol_inflation_share: string;
  /** pool_inflation_payout_rate ... */
  pool_inflation_payout_rate: string;
  /** max_voting_power_per_pool ... */
  max_voting_power_per_pool: string;
}

function createBaseParams(): Params {
  return { protocol_inflation_share: "", pool_inflation_payout_rate: "", max_voting_power_per_pool: "" };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol_inflation_share !== "") {
      writer.uint32(10).string(message.protocol_inflation_share);
    }
    if (message.pool_inflation_payout_rate !== "") {
      writer.uint32(18).string(message.pool_inflation_payout_rate);
    }
    if (message.max_voting_power_per_pool !== "") {
      writer.uint32(26).string(message.max_voting_power_per_pool);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.protocol_inflation_share = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pool_inflation_payout_rate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.max_voting_power_per_pool = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      protocol_inflation_share: isSet(object.protocol_inflation_share)
        ? globalThis.String(object.protocol_inflation_share)
        : "",
      pool_inflation_payout_rate: isSet(object.pool_inflation_payout_rate)
        ? globalThis.String(object.pool_inflation_payout_rate)
        : "",
      max_voting_power_per_pool: isSet(object.max_voting_power_per_pool)
        ? globalThis.String(object.max_voting_power_per_pool)
        : "",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.protocol_inflation_share !== "") {
      obj.protocol_inflation_share = message.protocol_inflation_share;
    }
    if (message.pool_inflation_payout_rate !== "") {
      obj.pool_inflation_payout_rate = message.pool_inflation_payout_rate;
    }
    if (message.max_voting_power_per_pool !== "") {
      obj.max_voting_power_per_pool = message.max_voting_power_per_pool;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.protocol_inflation_share = object.protocol_inflation_share ?? "";
    message.pool_inflation_payout_rate = object.pool_inflation_payout_rate ?? "";
    message.max_voting_power_per_pool = object.max_voting_power_per_pool ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
