// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: kyve/query/v1beta1/pools.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { BundleProposal } from "../../bundles/v1beta1/bundles";
import { Funding } from "../../funders/v1beta1/funders";
import { Pool, PoolStatus, poolStatusFromJSON, poolStatusToJSON } from "../../pool/v1beta1/pool";

export const protobufPackage = "kyve.query.v1beta1";

/** QueryPoolsRequest is the request type for the Query/Pools RPC method. */
export interface QueryPoolsRequest {
  /** pagination defines an optional pagination for the request. */
  pagination?:
    | PageRequest
    | undefined;
  /** search ... */
  search: string;
  /** runtime ... */
  runtime: string;
  /** disabled ... */
  disabled: boolean;
  /** storage_provider_id ... */
  storage_provider_id: number;
}

/** QueryPoolsResponse is the response type for the Query/Pools RPC method. */
export interface QueryPoolsResponse {
  /** pools ... */
  pools: PoolResponse[];
  /** pagination defines the pagination in the response. */
  pagination?: PageResponse | undefined;
}

/** PoolResponse ... */
export interface PoolResponse {
  /** id ... */
  id: string;
  /** data ... */
  data?:
    | Pool
    | undefined;
  /** bundle_proposal ... */
  bundle_proposal?:
    | BundleProposal
    | undefined;
  /** stakers ... */
  stakers: string[];
  /** total_stake ... */
  total_self_delegation: string;
  /** total_delegation ... */
  total_delegation: string;
  /** status ... */
  status: PoolStatus;
  /** account ... */
  account: string;
  /** account_balance ... */
  account_balance: string;
  /** funders ... */
  fundings: Funding[];
}

/** QueryPoolRequest is the request type for the Query/Pool RPC method. */
export interface QueryPoolRequest {
  /** id defines the unique ID of the pool. */
  id: string;
}

/** QueryPoolResponse is the response type for the Query/Pool RPC method. */
export interface QueryPoolResponse {
  /** pool ... */
  pool?: PoolResponse | undefined;
}

function createBaseQueryPoolsRequest(): QueryPoolsRequest {
  return { pagination: undefined, search: "", runtime: "", disabled: false, storage_provider_id: 0 };
}

export const QueryPoolsRequest = {
  encode(message: QueryPoolsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).ldelim();
    }
    if (message.search !== "") {
      writer.uint32(18).string(message.search);
    }
    if (message.runtime !== "") {
      writer.uint32(26).string(message.runtime);
    }
    if (message.disabled !== false) {
      writer.uint32(32).bool(message.disabled);
    }
    if (message.storage_provider_id !== 0) {
      writer.uint32(40).uint32(message.storage_provider_id);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryPoolsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPoolsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.search = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.runtime = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.disabled = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.storage_provider_id = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPoolsRequest {
    return {
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
      search: isSet(object.search) ? globalThis.String(object.search) : "",
      runtime: isSet(object.runtime) ? globalThis.String(object.runtime) : "",
      disabled: isSet(object.disabled) ? globalThis.Boolean(object.disabled) : false,
      storage_provider_id: isSet(object.storage_provider_id) ? globalThis.Number(object.storage_provider_id) : 0,
    };
  },

  toJSON(message: QueryPoolsRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    if (message.search !== "") {
      obj.search = message.search;
    }
    if (message.runtime !== "") {
      obj.runtime = message.runtime;
    }
    if (message.disabled !== false) {
      obj.disabled = message.disabled;
    }
    if (message.storage_provider_id !== 0) {
      obj.storage_provider_id = Math.round(message.storage_provider_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPoolsRequest>, I>>(base?: I): QueryPoolsRequest {
    return QueryPoolsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPoolsRequest>, I>>(object: I): QueryPoolsRequest {
    const message = createBaseQueryPoolsRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    message.search = object.search ?? "";
    message.runtime = object.runtime ?? "";
    message.disabled = object.disabled ?? false;
    message.storage_provider_id = object.storage_provider_id ?? 0;
    return message;
  },
};

function createBaseQueryPoolsResponse(): QueryPoolsResponse {
  return { pools: [], pagination: undefined };
}

export const QueryPoolsResponse = {
  encode(message: QueryPoolsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.pools) {
      PoolResponse.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryPoolsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPoolsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pools.push(PoolResponse.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPoolsResponse {
    return {
      pools: globalThis.Array.isArray(object?.pools) ? object.pools.map((e: any) => PoolResponse.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPoolsResponse): unknown {
    const obj: any = {};
    if (message.pools?.length) {
      obj.pools = message.pools.map((e) => PoolResponse.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPoolsResponse>, I>>(base?: I): QueryPoolsResponse {
    return QueryPoolsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPoolsResponse>, I>>(object: I): QueryPoolsResponse {
    const message = createBaseQueryPoolsResponse();
    message.pools = object.pools?.map((e) => PoolResponse.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBasePoolResponse(): PoolResponse {
  return {
    id: "0",
    data: undefined,
    bundle_proposal: undefined,
    stakers: [],
    total_self_delegation: "0",
    total_delegation: "0",
    status: 0,
    account: "",
    account_balance: "0",
    fundings: [],
  };
}

export const PoolResponse = {
  encode(message: PoolResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "0") {
      writer.uint32(8).uint64(message.id);
    }
    if (message.data !== undefined) {
      Pool.encode(message.data, writer.uint32(18).fork()).ldelim();
    }
    if (message.bundle_proposal !== undefined) {
      BundleProposal.encode(message.bundle_proposal, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.stakers) {
      writer.uint32(34).string(v!);
    }
    if (message.total_self_delegation !== "0") {
      writer.uint32(40).uint64(message.total_self_delegation);
    }
    if (message.total_delegation !== "0") {
      writer.uint32(48).uint64(message.total_delegation);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.account !== "") {
      writer.uint32(66).string(message.account);
    }
    if (message.account_balance !== "0") {
      writer.uint32(72).uint64(message.account_balance);
    }
    for (const v of message.fundings) {
      Funding.encode(v!, writer.uint32(82).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PoolResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToString(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.data = Pool.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bundle_proposal = BundleProposal.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.stakers.push(reader.string());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.total_self_delegation = longToString(reader.uint64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.total_delegation = longToString(reader.uint64() as Long);
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.account = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.account_balance = longToString(reader.uint64() as Long);
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.fundings.push(Funding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PoolResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      data: isSet(object.data) ? Pool.fromJSON(object.data) : undefined,
      bundle_proposal: isSet(object.bundle_proposal) ? BundleProposal.fromJSON(object.bundle_proposal) : undefined,
      stakers: globalThis.Array.isArray(object?.stakers) ? object.stakers.map((e: any) => globalThis.String(e)) : [],
      total_self_delegation: isSet(object.total_self_delegation)
        ? globalThis.String(object.total_self_delegation)
        : "0",
      total_delegation: isSet(object.total_delegation) ? globalThis.String(object.total_delegation) : "0",
      status: isSet(object.status) ? poolStatusFromJSON(object.status) : 0,
      account: isSet(object.account) ? globalThis.String(object.account) : "",
      account_balance: isSet(object.account_balance) ? globalThis.String(object.account_balance) : "0",
      fundings: globalThis.Array.isArray(object?.fundings) ? object.fundings.map((e: any) => Funding.fromJSON(e)) : [],
    };
  },

  toJSON(message: PoolResponse): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.data !== undefined) {
      obj.data = Pool.toJSON(message.data);
    }
    if (message.bundle_proposal !== undefined) {
      obj.bundle_proposal = BundleProposal.toJSON(message.bundle_proposal);
    }
    if (message.stakers?.length) {
      obj.stakers = message.stakers;
    }
    if (message.total_self_delegation !== "0") {
      obj.total_self_delegation = message.total_self_delegation;
    }
    if (message.total_delegation !== "0") {
      obj.total_delegation = message.total_delegation;
    }
    if (message.status !== 0) {
      obj.status = poolStatusToJSON(message.status);
    }
    if (message.account !== "") {
      obj.account = message.account;
    }
    if (message.account_balance !== "0") {
      obj.account_balance = message.account_balance;
    }
    if (message.fundings?.length) {
      obj.fundings = message.fundings.map((e) => Funding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PoolResponse>, I>>(base?: I): PoolResponse {
    return PoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PoolResponse>, I>>(object: I): PoolResponse {
    const message = createBasePoolResponse();
    message.id = object.id ?? "0";
    message.data = (object.data !== undefined && object.data !== null) ? Pool.fromPartial(object.data) : undefined;
    message.bundle_proposal = (object.bundle_proposal !== undefined && object.bundle_proposal !== null)
      ? BundleProposal.fromPartial(object.bundle_proposal)
      : undefined;
    message.stakers = object.stakers?.map((e) => e) || [];
    message.total_self_delegation = object.total_self_delegation ?? "0";
    message.total_delegation = object.total_delegation ?? "0";
    message.status = object.status ?? 0;
    message.account = object.account ?? "";
    message.account_balance = object.account_balance ?? "0";
    message.fundings = object.fundings?.map((e) => Funding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryPoolRequest(): QueryPoolRequest {
  return { id: "0" };
}

export const QueryPoolRequest = {
  encode(message: QueryPoolRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "0") {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryPoolRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPoolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToString(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPoolRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "0" };
  },

  toJSON(message: QueryPoolRequest): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPoolRequest>, I>>(base?: I): QueryPoolRequest {
    return QueryPoolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPoolRequest>, I>>(object: I): QueryPoolRequest {
    const message = createBaseQueryPoolRequest();
    message.id = object.id ?? "0";
    return message;
  },
};

function createBaseQueryPoolResponse(): QueryPoolResponse {
  return { pool: undefined };
}

export const QueryPoolResponse = {
  encode(message: QueryPoolResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pool !== undefined) {
      PoolResponse.encode(message.pool, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryPoolResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.pool = PoolResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPoolResponse {
    return { pool: isSet(object.pool) ? PoolResponse.fromJSON(object.pool) : undefined };
  },

  toJSON(message: QueryPoolResponse): unknown {
    const obj: any = {};
    if (message.pool !== undefined) {
      obj.pool = PoolResponse.toJSON(message.pool);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPoolResponse>, I>>(base?: I): QueryPoolResponse {
    return QueryPoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPoolResponse>, I>>(object: I): QueryPoolResponse {
    const message = createBaseQueryPoolResponse();
    message.pool = (object.pool !== undefined && object.pool !== null)
      ? PoolResponse.fromPartial(object.pool)
      : undefined;
    return message;
  },
};

/** QueryPool ... */
export interface QueryPool {
  /** Pools queries for all pools. */
  Pools(request: QueryPoolsRequest): Promise<QueryPoolsResponse>;
  /** Pool queries a pool by its Id. */
  Pool(request: QueryPoolRequest): Promise<QueryPoolResponse>;
}

export const QueryPoolServiceName = "kyve.query.v1beta1.QueryPool";
export class QueryPoolClientImpl implements QueryPool {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryPoolServiceName;
    this.rpc = rpc;
    this.Pools = this.Pools.bind(this);
    this.Pool = this.Pool.bind(this);
  }
  Pools(request: QueryPoolsRequest): Promise<QueryPoolsResponse> {
    const data = QueryPoolsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Pools", data);
    return promise.then((data) => QueryPoolsResponse.decode(_m0.Reader.create(data)));
  }

  Pool(request: QueryPoolRequest): Promise<QueryPoolResponse> {
    const data = QueryPoolRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Pool", data);
    return promise.then((data) => QueryPoolResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
