// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kyve/stakers/v1/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import {
  CommissionChangeEntry,
  LeavePoolEntry,
  PoolAccount,
  QueueState,
  StakeFractionChangeEntry,
  Staker,
} from "./stakers";

export const protobufPackage = "kyve.stakers.v1";

/** GenesisState defines the stakers module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params?:
    | Params
    | undefined;
  /** staker_list ... */
  staker_list: Staker[];
  /** pool_account_list ... */
  pool_account_list: PoolAccount[];
  /** commission_change_entries ... */
  commission_change_entries: CommissionChangeEntry[];
  /** queue_state_commission ... */
  queue_state_commission?:
    | QueueState
    | undefined;
  /** leave_pool_entries ... */
  leave_pool_entries: LeavePoolEntry[];
  /** queue_state_leave ... */
  queue_state_leave?:
    | QueueState
    | undefined;
  /** stake_fraction_change_entries ... */
  stake_fraction_change_entries: StakeFractionChangeEntry[];
  /** queue_state_stake_fraction ... */
  queue_state_stake_fraction?: QueueState | undefined;
}

function createBaseGenesisState(): GenesisState {
  return {
    params: undefined,
    staker_list: [],
    pool_account_list: [],
    commission_change_entries: [],
    queue_state_commission: undefined,
    leave_pool_entries: [],
    queue_state_leave: undefined,
    stake_fraction_change_entries: [],
    queue_state_stake_fraction: undefined,
  };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.staker_list) {
      Staker.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.pool_account_list) {
      PoolAccount.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.commission_change_entries) {
      CommissionChangeEntry.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.queue_state_commission !== undefined) {
      QueueState.encode(message.queue_state_commission, writer.uint32(42).fork()).join();
    }
    for (const v of message.leave_pool_entries) {
      LeavePoolEntry.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.queue_state_leave !== undefined) {
      QueueState.encode(message.queue_state_leave, writer.uint32(58).fork()).join();
    }
    for (const v of message.stake_fraction_change_entries) {
      StakeFractionChangeEntry.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.queue_state_stake_fraction !== undefined) {
      QueueState.encode(message.queue_state_stake_fraction, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.staker_list.push(Staker.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pool_account_list.push(PoolAccount.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.commission_change_entries.push(CommissionChangeEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.queue_state_commission = QueueState.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.leave_pool_entries.push(LeavePoolEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.queue_state_leave = QueueState.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.stake_fraction_change_entries.push(StakeFractionChangeEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.queue_state_stake_fraction = QueueState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      staker_list: globalThis.Array.isArray(object?.staker_list)
        ? object.staker_list.map((e: any) => Staker.fromJSON(e))
        : [],
      pool_account_list: globalThis.Array.isArray(object?.pool_account_list)
        ? object.pool_account_list.map((e: any) => PoolAccount.fromJSON(e))
        : [],
      commission_change_entries: globalThis.Array.isArray(object?.commission_change_entries)
        ? object.commission_change_entries.map((e: any) => CommissionChangeEntry.fromJSON(e))
        : [],
      queue_state_commission: isSet(object.queue_state_commission)
        ? QueueState.fromJSON(object.queue_state_commission)
        : undefined,
      leave_pool_entries: globalThis.Array.isArray(object?.leave_pool_entries)
        ? object.leave_pool_entries.map((e: any) => LeavePoolEntry.fromJSON(e))
        : [],
      queue_state_leave: isSet(object.queue_state_leave) ? QueueState.fromJSON(object.queue_state_leave) : undefined,
      stake_fraction_change_entries: globalThis.Array.isArray(object?.stake_fraction_change_entries)
        ? object.stake_fraction_change_entries.map((e: any) => StakeFractionChangeEntry.fromJSON(e))
        : [],
      queue_state_stake_fraction: isSet(object.queue_state_stake_fraction)
        ? QueueState.fromJSON(object.queue_state_stake_fraction)
        : undefined,
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.staker_list?.length) {
      obj.staker_list = message.staker_list.map((e) => Staker.toJSON(e));
    }
    if (message.pool_account_list?.length) {
      obj.pool_account_list = message.pool_account_list.map((e) => PoolAccount.toJSON(e));
    }
    if (message.commission_change_entries?.length) {
      obj.commission_change_entries = message.commission_change_entries.map((e) => CommissionChangeEntry.toJSON(e));
    }
    if (message.queue_state_commission !== undefined) {
      obj.queue_state_commission = QueueState.toJSON(message.queue_state_commission);
    }
    if (message.leave_pool_entries?.length) {
      obj.leave_pool_entries = message.leave_pool_entries.map((e) => LeavePoolEntry.toJSON(e));
    }
    if (message.queue_state_leave !== undefined) {
      obj.queue_state_leave = QueueState.toJSON(message.queue_state_leave);
    }
    if (message.stake_fraction_change_entries?.length) {
      obj.stake_fraction_change_entries = message.stake_fraction_change_entries.map((e) =>
        StakeFractionChangeEntry.toJSON(e)
      );
    }
    if (message.queue_state_stake_fraction !== undefined) {
      obj.queue_state_stake_fraction = QueueState.toJSON(message.queue_state_stake_fraction);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.staker_list = object.staker_list?.map((e) => Staker.fromPartial(e)) || [];
    message.pool_account_list = object.pool_account_list?.map((e) => PoolAccount.fromPartial(e)) || [];
    message.commission_change_entries =
      object.commission_change_entries?.map((e) => CommissionChangeEntry.fromPartial(e)) || [];
    message.queue_state_commission =
      (object.queue_state_commission !== undefined && object.queue_state_commission !== null)
        ? QueueState.fromPartial(object.queue_state_commission)
        : undefined;
    message.leave_pool_entries = object.leave_pool_entries?.map((e) => LeavePoolEntry.fromPartial(e)) || [];
    message.queue_state_leave = (object.queue_state_leave !== undefined && object.queue_state_leave !== null)
      ? QueueState.fromPartial(object.queue_state_leave)
      : undefined;
    message.stake_fraction_change_entries =
      object.stake_fraction_change_entries?.map((e) => StakeFractionChangeEntry.fromPartial(e)) || [];
    message.queue_state_stake_fraction =
      (object.queue_state_stake_fraction !== undefined && object.queue_state_stake_fraction !== null)
        ? QueueState.fromPartial(object.queue_state_stake_fraction)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
