# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: password.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epassword.proto\"U\n\x0fPasswordDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\thashValue\x18\x03 \x01(\t\x12\x11\n\tsaltValue\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"3\n\x0cPasswordList\x12#\n\tpasswords\x18\x01 \x03(\x0b\x32\x10.PasswordDetails2\xb5\x01\n\x0fPasswordService\x12,\n\x11RetrievePasswords\x12\x06.Empty\x1a\r.PasswordList\"\x00\x12\x35\n\rAddNewDetails\x12\x10.PasswordDetails\x1a\x10.PasswordDetails\"\x00\x12=\n\x15UpdatePasswordDetails\x12\x10.PasswordDetails\x1a\x10.PasswordDetails\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'password_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PASSWORDDETAILS']._serialized_start=18
  _globals['_PASSWORDDETAILS']._serialized_end=103
  _globals['_EMPTY']._serialized_start=105
  _globals['_EMPTY']._serialized_end=112
  _globals['_PASSWORDLIST']._serialized_start=114
  _globals['_PASSWORDLIST']._serialized_end=165
  _globals['_PASSWORDSERVICE']._serialized_start=168
  _globals['_PASSWORDSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
