# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import password_pb2 as password__pb2


class PasswordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrievePasswords = channel.unary_unary(
                '/PasswordService/RetrievePasswords',
                request_serializer=password__pb2.Empty.SerializeToString,
                response_deserializer=password__pb2.PasswordList.FromString,
                )
        self.AddNewDetails = channel.unary_unary(
                '/PasswordService/AddNewDetails',
                request_serializer=password__pb2.PasswordDetails.SerializeToString,
                response_deserializer=password__pb2.PasswordDetails.FromString,
                )
        self.UpdatePasswordDetails = channel.unary_unary(
                '/PasswordService/UpdatePasswordDetails',
                request_serializer=password__pb2.PasswordDetails.SerializeToString,
                response_deserializer=password__pb2.PasswordDetails.FromString,
                )


class PasswordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrievePasswords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNewDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePasswordDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasswordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrievePasswords': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrievePasswords,
                    request_deserializer=password__pb2.Empty.FromString,
                    response_serializer=password__pb2.PasswordList.SerializeToString,
            ),
            'AddNewDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNewDetails,
                    request_deserializer=password__pb2.PasswordDetails.FromString,
                    response_serializer=password__pb2.PasswordDetails.SerializeToString,
            ),
            'UpdatePasswordDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePasswordDetails,
                    request_deserializer=password__pb2.PasswordDetails.FromString,
                    response_serializer=password__pb2.PasswordDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PasswordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PasswordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrievePasswords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PasswordService/RetrievePasswords',
            password__pb2.Empty.SerializeToString,
            password__pb2.PasswordList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddNewDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PasswordService/AddNewDetails',
            password__pb2.PasswordDetails.SerializeToString,
            password__pb2.PasswordDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePasswordDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PasswordService/UpdatePasswordDetails',
            password__pb2.PasswordDetails.SerializeToString,
            password__pb2.PasswordDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
