// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: kyverdk/runtime/v1/runtime.proto

package v1

import (
	types "github.com/KYVENetwork/chain/x/bundles/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The main data entity served by the gRPC service
// Contains the block key and the block value as a serialized value
type DataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key of the data item
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the data item
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *DataItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Configuration entity containing serialized info about connection to the respective chain
type RuntimeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The serialized configuration
	SerializedConfig string `protobuf:"bytes,1,opt,name=serialized_config,json=serializedConfig,proto3" json:"serialized_config,omitempty"`
}

func (x *RuntimeConfig) Reset() {
	*x = RuntimeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfig) ProtoMessage() {}

func (x *RuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfig.ProtoReflect.Descriptor instead.
func (*RuntimeConfig) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeConfig) GetSerializedConfig() string {
	if x != nil {
		return x.SerializedConfig
	}
	return ""
}

// GetRuntimeNameRequest
// Request returning the name of the runtime
// returns the runtime name as a string
type GetRuntimeNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRuntimeNameRequest) Reset() {
	*x = GetRuntimeNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuntimeNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeNameRequest) ProtoMessage() {}

func (x *GetRuntimeNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeNameRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeNameRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

// GetRuntimeNameResponse
// Response returning the name of the runtime
// returns the runtime name as a string
type GetRuntimeNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the runtime
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRuntimeNameResponse) Reset() {
	*x = GetRuntimeNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuntimeNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeNameResponse) ProtoMessage() {}

func (x *GetRuntimeNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeNameResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeNameResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *GetRuntimeNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetRuntimeVersionRequest
// Request returning the version of the runtime
// returns the runtime version as a string
type GetRuntimeVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRuntimeVersionRequest) Reset() {
	*x = GetRuntimeVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuntimeVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeVersionRequest) ProtoMessage() {}

func (x *GetRuntimeVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeVersionRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeVersionRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

// GetRuntimeVersionResponse
// Response returning the version of the runtime
// returns the runtime version as a string
type GetRuntimeVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The version of the runtime
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRuntimeVersionResponse) Reset() {
	*x = GetRuntimeVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuntimeVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeVersionResponse) ProtoMessage() {}

func (x *GetRuntimeVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeVersionResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeVersionResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *GetRuntimeVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ValidateSetConfigRequest
// Request validating a configuration string to connect to the respective chain
// returns a validated serialized configuration object
type ValidateSetConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw configuration string
	RawConfig string `protobuf:"bytes,1,opt,name=raw_config,json=rawConfig,proto3" json:"raw_config,omitempty"`
}

func (x *ValidateSetConfigRequest) Reset() {
	*x = ValidateSetConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateSetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSetConfigRequest) ProtoMessage() {}

func (x *ValidateSetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSetConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateSetConfigRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateSetConfigRequest) GetRawConfig() string {
	if x != nil {
		return x.RawConfig
	}
	return ""
}

// ValidateSetConfigResponse
// Response validating a configuration string to connect to the respective chain
// returns a validated serialized configuration object
type ValidateSetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The validated serialized configuration object
	SerializedConfig string `protobuf:"bytes,1,opt,name=serialized_config,json=serializedConfig,proto3" json:"serialized_config,omitempty"`
}

func (x *ValidateSetConfigResponse) Reset() {
	*x = ValidateSetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateSetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSetConfigResponse) ProtoMessage() {}

func (x *ValidateSetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSetConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateSetConfigResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateSetConfigResponse) GetSerializedConfig() string {
	if x != nil {
		return x.SerializedConfig
	}
	return ""
}

// GetDataItemRequest
// Request retrieving and returning a block from the respective chain
// Returns the requested block as a dataItem
type GetDataItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The key of the data item
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetDataItemRequest) Reset() {
	*x = GetDataItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataItemRequest) ProtoMessage() {}

func (x *GetDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataItemRequest.ProtoReflect.Descriptor instead.
func (*GetDataItemRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *GetDataItemRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetDataItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetDataItemResponse
// Response retrieving and returning a block from the respective chain
// Returns the requested block as a dataItem
type GetDataItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The data item
	DataItem *DataItem `protobuf:"bytes,1,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
}

func (x *GetDataItemResponse) Reset() {
	*x = GetDataItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataItemResponse) ProtoMessage() {}

func (x *GetDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataItemResponse.ProtoReflect.Descriptor instead.
func (*GetDataItemResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *GetDataItemResponse) GetDataItem() *DataItem {
	if x != nil {
		return x.DataItem
	}
	return nil
}

// PrevalidateDataItemRequest
// Request pre-validating a dataItem that is about to be validated
// returns the pre-validation result as a boolean
type PrevalidateDataItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The data item to be pre-validated
	DataItem *DataItem `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
}

func (x *PrevalidateDataItemRequest) Reset() {
	*x = PrevalidateDataItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrevalidateDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrevalidateDataItemRequest) ProtoMessage() {}

func (x *PrevalidateDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrevalidateDataItemRequest.ProtoReflect.Descriptor instead.
func (*PrevalidateDataItemRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *PrevalidateDataItemRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PrevalidateDataItemRequest) GetDataItem() *DataItem {
	if x != nil {
		return x.DataItem
	}
	return nil
}

// PrevalidateDataItemResponse
// Response pre-validating a dataItem that is about to be validated
// returns the pre-validation result as a boolean
type PrevalidateDataItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pre-validation result
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// The pre-validation error message
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PrevalidateDataItemResponse) Reset() {
	*x = PrevalidateDataItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrevalidateDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrevalidateDataItemResponse) ProtoMessage() {}

func (x *PrevalidateDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrevalidateDataItemResponse.ProtoReflect.Descriptor instead.
func (*PrevalidateDataItemResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *PrevalidateDataItemResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *PrevalidateDataItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TransformDataItemRequest
// Request transforming the given data item into a preferred format
// returns the transformed dataItem
type TransformDataItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The data item to be transformed
	DataItem *DataItem `protobuf:"bytes,2,opt,name=data_item,json=dataItem,proto3" json:"data_item,omitempty"`
}

func (x *TransformDataItemRequest) Reset() {
	*x = TransformDataItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformDataItemRequest) ProtoMessage() {}

func (x *TransformDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformDataItemRequest.ProtoReflect.Descriptor instead.
func (*TransformDataItemRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *TransformDataItemRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TransformDataItemRequest) GetDataItem() *DataItem {
	if x != nil {
		return x.DataItem
	}
	return nil
}

// TransformDataItemResponse
// Response transforming the given data item into a preferred format
// returns the transformed dataItem
type TransformDataItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The transformed data item
	TransformedDataItem *DataItem `protobuf:"bytes,1,opt,name=transformed_data_item,json=transformedDataItem,proto3" json:"transformed_data_item,omitempty"`
}

func (x *TransformDataItemResponse) Reset() {
	*x = TransformDataItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformDataItemResponse) ProtoMessage() {}

func (x *TransformDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformDataItemResponse.ProtoReflect.Descriptor instead.
func (*TransformDataItemResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *TransformDataItemResponse) GetTransformedDataItem() *DataItem {
	if x != nil {
		return x.TransformedDataItem
	}
	return nil
}

// ValidateDataItemRequest
// Request validating a dataItem
// returns the validation result as a boolean
type ValidateDataItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The proposed data item
	ProposedDataItem *DataItem `protobuf:"bytes,2,opt,name=proposed_data_item,json=proposedDataItem,proto3" json:"proposed_data_item,omitempty"`
	// The data item to be validated
	ValidationDataItem *DataItem `protobuf:"bytes,3,opt,name=validation_data_item,json=validationDataItem,proto3" json:"validation_data_item,omitempty"`
}

func (x *ValidateDataItemRequest) Reset() {
	*x = ValidateDataItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDataItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDataItemRequest) ProtoMessage() {}

func (x *ValidateDataItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDataItemRequest.ProtoReflect.Descriptor instead.
func (*ValidateDataItemRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateDataItemRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ValidateDataItemRequest) GetProposedDataItem() *DataItem {
	if x != nil {
		return x.ProposedDataItem
	}
	return nil
}

func (x *ValidateDataItemRequest) GetValidationDataItem() *DataItem {
	if x != nil {
		return x.ValidationDataItem
	}
	return nil
}

// ValidateDataItemResponse
// Response validating a dataItem
// returns the validation result as a boolean
type ValidateDataItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The validation result as vote
	Vote types.VoteType `protobuf:"varint,1,opt,name=vote,proto3,enum=kyve.bundles.v1beta1.VoteType" json:"vote,omitempty"`
}

func (x *ValidateDataItemResponse) Reset() {
	*x = ValidateDataItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDataItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDataItemResponse) ProtoMessage() {}

func (x *ValidateDataItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDataItemResponse.ProtoReflect.Descriptor instead.
func (*ValidateDataItemResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateDataItemResponse) GetVote() types.VoteType {
	if x != nil {
		return x.Vote
	}
	return types.VoteType(0)
}

// SummarizeDataBundleRequest
// Request summarizing a dataBundle
// returns the bundle summary as a string
type SummarizeDataBundleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The data items to be summarized
	Bundle []*DataItem `protobuf:"bytes,2,rep,name=bundle,proto3" json:"bundle,omitempty"`
}

func (x *SummarizeDataBundleRequest) Reset() {
	*x = SummarizeDataBundleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummarizeDataBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeDataBundleRequest) ProtoMessage() {}

func (x *SummarizeDataBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeDataBundleRequest.ProtoReflect.Descriptor instead.
func (*SummarizeDataBundleRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *SummarizeDataBundleRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SummarizeDataBundleRequest) GetBundle() []*DataItem {
	if x != nil {
		return x.Bundle
	}
	return nil
}

// SummarizeDataBundleResponse
// Response summarizing a dataBundle
// returns the bundle summary as a string
type SummarizeDataBundleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The bundle summary
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *SummarizeDataBundleResponse) Reset() {
	*x = SummarizeDataBundleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummarizeDataBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeDataBundleResponse) ProtoMessage() {}

func (x *SummarizeDataBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeDataBundleResponse.ProtoReflect.Descriptor instead.
func (*SummarizeDataBundleResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *SummarizeDataBundleResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// NextKeyRequest
// Request retrieving the next key on the chain
// returns the key as a string
type NextKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The configuration object
	Config *RuntimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The current key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *NextKeyRequest) Reset() {
	*x = NextKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextKeyRequest) ProtoMessage() {}

func (x *NextKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextKeyRequest.ProtoReflect.Descriptor instead.
func (*NextKeyRequest) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *NextKeyRequest) GetConfig() *RuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NextKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// NextKeyResponse
// Response retrieving the next key on the chain
// returns the key as a string
type NextKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The next key
	NextKey string `protobuf:"bytes,1,opt,name=next_key,json=nextKey,proto3" json:"next_key,omitempty"`
}

func (x *NextKeyResponse) Reset() {
	*x = NextKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextKeyResponse) ProtoMessage() {}

func (x *NextKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyverdk_runtime_v1_runtime_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextKeyResponse.ProtoReflect.Descriptor instead.
func (*NextKeyResponse) Descriptor() ([]byte, []int) {
	return file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *NextKeyResponse) GetNextKey() string {
	if x != nil {
		return x.NextKey
	}
	return ""
}

var File_kyverdk_runtime_v1_runtime_proto protoreflect.FileDescriptor

var file_kyverdk_runtime_v1_runtime_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x6b, 0x79, 0x76, 0x65, 0x2f, 0x62, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x74, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x0d, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x39, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x61, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x48, 0x0a, 0x19,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b,
	0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x50, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x92, 0x01, 0x0a, 0x1a,
	0x50, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x79, 0x76,
	0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72,
	0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x49, 0x0a, 0x1b, 0x50, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x18,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72,
	0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x6d,
	0x0a, 0x19, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x15, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76,
	0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x22, 0xf0, 0x01,
	0x0a, 0x17, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x79, 0x76, 0x65,
	0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x4a, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10,
	0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x4e, 0x0a, 0x14, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x12, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x4e, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04,
	0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6b, 0x79, 0x76,
	0x65, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65,
	0x22, 0x8d, 0x01, 0x0a, 0x1a, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x06, 0x62, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x79, 0x76,
	0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x22, 0x37, 0x0a, 0x1b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x5d, 0x0a, 0x0e, 0x4e, 0x65, 0x78,
	0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x79,
	0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x0f, 0x4e, 0x65, 0x78, 0x74,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x32, 0xe2, 0x07, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x2e, 0x6b, 0x79,
	0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x70, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64,
	0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x11, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2c, 0x2e, 0x6b, 0x79, 0x76, 0x65,
	0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64,
	0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x76, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2e, 0x2e,
	0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70,
	0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x2c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2d, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6d, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2c, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x76, 0x0a, 0x13, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x2e, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x07, 0x4e, 0x65, 0x78, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x22, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6b, 0x79, 0x76, 0x65, 0x72, 0x64, 0x6b,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x78, 0x74,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x59, 0x56, 0x45, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6b, 0x79, 0x76, 0x65, 0x6a, 0x73, 0x2f, 0x6b, 0x79, 0x76,
	0x65, 0x72, 0x64, 0x6b, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kyverdk_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_kyverdk_runtime_v1_runtime_proto_rawDescData = file_kyverdk_runtime_v1_runtime_proto_rawDesc
)

func file_kyverdk_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_kyverdk_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_kyverdk_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_kyverdk_runtime_v1_runtime_proto_rawDescData)
	})
	return file_kyverdk_runtime_v1_runtime_proto_rawDescData
}

var file_kyverdk_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_kyverdk_runtime_v1_runtime_proto_goTypes = []interface{}{
	(*DataItem)(nil),                    // 0: kyverdk.runtime.v1.DataItem
	(*RuntimeConfig)(nil),               // 1: kyverdk.runtime.v1.RuntimeConfig
	(*GetRuntimeNameRequest)(nil),       // 2: kyverdk.runtime.v1.GetRuntimeNameRequest
	(*GetRuntimeNameResponse)(nil),      // 3: kyverdk.runtime.v1.GetRuntimeNameResponse
	(*GetRuntimeVersionRequest)(nil),    // 4: kyverdk.runtime.v1.GetRuntimeVersionRequest
	(*GetRuntimeVersionResponse)(nil),   // 5: kyverdk.runtime.v1.GetRuntimeVersionResponse
	(*ValidateSetConfigRequest)(nil),    // 6: kyverdk.runtime.v1.ValidateSetConfigRequest
	(*ValidateSetConfigResponse)(nil),   // 7: kyverdk.runtime.v1.ValidateSetConfigResponse
	(*GetDataItemRequest)(nil),          // 8: kyverdk.runtime.v1.GetDataItemRequest
	(*GetDataItemResponse)(nil),         // 9: kyverdk.runtime.v1.GetDataItemResponse
	(*PrevalidateDataItemRequest)(nil),  // 10: kyverdk.runtime.v1.PrevalidateDataItemRequest
	(*PrevalidateDataItemResponse)(nil), // 11: kyverdk.runtime.v1.PrevalidateDataItemResponse
	(*TransformDataItemRequest)(nil),    // 12: kyverdk.runtime.v1.TransformDataItemRequest
	(*TransformDataItemResponse)(nil),   // 13: kyverdk.runtime.v1.TransformDataItemResponse
	(*ValidateDataItemRequest)(nil),     // 14: kyverdk.runtime.v1.ValidateDataItemRequest
	(*ValidateDataItemResponse)(nil),    // 15: kyverdk.runtime.v1.ValidateDataItemResponse
	(*SummarizeDataBundleRequest)(nil),  // 16: kyverdk.runtime.v1.SummarizeDataBundleRequest
	(*SummarizeDataBundleResponse)(nil), // 17: kyverdk.runtime.v1.SummarizeDataBundleResponse
	(*NextKeyRequest)(nil),              // 18: kyverdk.runtime.v1.NextKeyRequest
	(*NextKeyResponse)(nil),             // 19: kyverdk.runtime.v1.NextKeyResponse
	(types.VoteType)(0),                 // 20: kyve.bundles.v1beta1.VoteType
}
var file_kyverdk_runtime_v1_runtime_proto_depIdxs = []int32{
	1,  // 0: kyverdk.runtime.v1.GetDataItemRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	0,  // 1: kyverdk.runtime.v1.GetDataItemResponse.data_item:type_name -> kyverdk.runtime.v1.DataItem
	1,  // 2: kyverdk.runtime.v1.PrevalidateDataItemRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	0,  // 3: kyverdk.runtime.v1.PrevalidateDataItemRequest.data_item:type_name -> kyverdk.runtime.v1.DataItem
	1,  // 4: kyverdk.runtime.v1.TransformDataItemRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	0,  // 5: kyverdk.runtime.v1.TransformDataItemRequest.data_item:type_name -> kyverdk.runtime.v1.DataItem
	0,  // 6: kyverdk.runtime.v1.TransformDataItemResponse.transformed_data_item:type_name -> kyverdk.runtime.v1.DataItem
	1,  // 7: kyverdk.runtime.v1.ValidateDataItemRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	0,  // 8: kyverdk.runtime.v1.ValidateDataItemRequest.proposed_data_item:type_name -> kyverdk.runtime.v1.DataItem
	0,  // 9: kyverdk.runtime.v1.ValidateDataItemRequest.validation_data_item:type_name -> kyverdk.runtime.v1.DataItem
	20, // 10: kyverdk.runtime.v1.ValidateDataItemResponse.vote:type_name -> kyve.bundles.v1beta1.VoteType
	1,  // 11: kyverdk.runtime.v1.SummarizeDataBundleRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	0,  // 12: kyverdk.runtime.v1.SummarizeDataBundleRequest.bundle:type_name -> kyverdk.runtime.v1.DataItem
	1,  // 13: kyverdk.runtime.v1.NextKeyRequest.config:type_name -> kyverdk.runtime.v1.RuntimeConfig
	2,  // 14: kyverdk.runtime.v1.RuntimeService.GetRuntimeName:input_type -> kyverdk.runtime.v1.GetRuntimeNameRequest
	4,  // 15: kyverdk.runtime.v1.RuntimeService.GetRuntimeVersion:input_type -> kyverdk.runtime.v1.GetRuntimeVersionRequest
	6,  // 16: kyverdk.runtime.v1.RuntimeService.ValidateSetConfig:input_type -> kyverdk.runtime.v1.ValidateSetConfigRequest
	8,  // 17: kyverdk.runtime.v1.RuntimeService.GetDataItem:input_type -> kyverdk.runtime.v1.GetDataItemRequest
	10, // 18: kyverdk.runtime.v1.RuntimeService.PrevalidateDataItem:input_type -> kyverdk.runtime.v1.PrevalidateDataItemRequest
	12, // 19: kyverdk.runtime.v1.RuntimeService.TransformDataItem:input_type -> kyverdk.runtime.v1.TransformDataItemRequest
	14, // 20: kyverdk.runtime.v1.RuntimeService.ValidateDataItem:input_type -> kyverdk.runtime.v1.ValidateDataItemRequest
	16, // 21: kyverdk.runtime.v1.RuntimeService.SummarizeDataBundle:input_type -> kyverdk.runtime.v1.SummarizeDataBundleRequest
	18, // 22: kyverdk.runtime.v1.RuntimeService.NextKey:input_type -> kyverdk.runtime.v1.NextKeyRequest
	3,  // 23: kyverdk.runtime.v1.RuntimeService.GetRuntimeName:output_type -> kyverdk.runtime.v1.GetRuntimeNameResponse
	5,  // 24: kyverdk.runtime.v1.RuntimeService.GetRuntimeVersion:output_type -> kyverdk.runtime.v1.GetRuntimeVersionResponse
	7,  // 25: kyverdk.runtime.v1.RuntimeService.ValidateSetConfig:output_type -> kyverdk.runtime.v1.ValidateSetConfigResponse
	9,  // 26: kyverdk.runtime.v1.RuntimeService.GetDataItem:output_type -> kyverdk.runtime.v1.GetDataItemResponse
	11, // 27: kyverdk.runtime.v1.RuntimeService.PrevalidateDataItem:output_type -> kyverdk.runtime.v1.PrevalidateDataItemResponse
	13, // 28: kyverdk.runtime.v1.RuntimeService.TransformDataItem:output_type -> kyverdk.runtime.v1.TransformDataItemResponse
	15, // 29: kyverdk.runtime.v1.RuntimeService.ValidateDataItem:output_type -> kyverdk.runtime.v1.ValidateDataItemResponse
	17, // 30: kyverdk.runtime.v1.RuntimeService.SummarizeDataBundle:output_type -> kyverdk.runtime.v1.SummarizeDataBundleResponse
	19, // 31: kyverdk.runtime.v1.RuntimeService.NextKey:output_type -> kyverdk.runtime.v1.NextKeyResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_kyverdk_runtime_v1_runtime_proto_init() }
func file_kyverdk_runtime_v1_runtime_proto_init() {
	if File_kyverdk_runtime_v1_runtime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuntimeNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuntimeNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuntimeVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuntimeVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateSetConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateSetConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrevalidateDataItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrevalidateDataItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformDataItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformDataItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDataItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDataItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummarizeDataBundleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummarizeDataBundleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyverdk_runtime_v1_runtime_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kyverdk_runtime_v1_runtime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyverdk_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_kyverdk_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_kyverdk_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_kyverdk_runtime_v1_runtime_proto = out.File
	file_kyverdk_runtime_v1_runtime_proto_rawDesc = nil
	file_kyverdk_runtime_v1_runtime_proto_goTypes = nil
	file_kyverdk_runtime_v1_runtime_proto_depIdxs = nil
}
