###############################################################################
###                          Formatting & Linting                           ###
###############################################################################

format:
	@echo "📝 Running formatter..."
	@yarn format
	@echo "✅ Completed formatting!"

lint:
	@echo "📝 Running linter..."
	@yarn lint
	@echo "✅ Completed linting!"