// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: kyve/stakers/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { SlashType, slashTypeFromJSON, slashTypeToJSON, slashTypeToNumber } from "./stakers";

export const protobufPackage = "kyve.stakers.v1";

/**
 * EventUpdateParams is an event emitted when the module parameters are updated.
 * emitted_by: MsgUpdateParams
 */
export interface EventUpdateParams {
  /** old_params is the module's old parameters. */
  old_params?:
    | Params
    | undefined;
  /** new_params is the module's new parameters. */
  new_params?:
    | Params
    | undefined;
  /** payload is the parameter updates that were performed. */
  payload: string;
}

/**
 * EventUpdateCommission ...
 * emitted_by: EndBlock
 */
export interface EventUpdateCommission {
  /** staker is the account address of the protocol node. */
  staker: string;
  /** pool_id ... */
  pool_id: string;
  /** commission ... */
  commission: string;
}

/**
 * EventUpdateCommission ...
 * emitted_by: MsgUpdateStakeFraction, EndBlock
 */
export interface EventUpdateStakeFraction {
  /** staker is the account address of the protocol node. */
  staker: string;
  /** pool_id ... */
  pool_id: string;
  /** stake_fraction ... */
  stake_fraction: string;
}

/**
 * EventClaimCommissionRewards ...
 * emitted_by: MsgClaimCommissionRewards
 */
export interface EventClaimCommissionRewards {
  /** staker is the account address of the protocol node. */
  staker: string;
  /** amounts is the amount of the commission rewards claimed */
  amounts: string;
}

/**
 * EventJoinPool ...
 * emitted_by: MsgJoinPool
 */
export interface EventJoinPool {
  /** pool_id is the pool the staker joined */
  pool_id: string;
  /** staker is the address of the staker */
  staker: string;
  /**
   * pool_address is the address of the protocol node which
   * votes in favor of the staker
   */
  pool_address: string;
  /** amount is the amount of funds transferred to the pool address */
  amount: string;
  /** commission ... */
  commission: string;
  /** stake_fraction ... */
  stake_fraction: string;
}

/**
 * EventLeavePool ...
 * emitted_by: EndBlock
 */
export interface EventLeavePool {
  /** pool_id ... */
  pool_id: string;
  /** staker ... */
  staker: string;
}

/**
 * EventSlash is an event emitted when a protocol node is slashed.
 * emitted_by: MsgSubmitBundleProposal, EndBlock
 */
export interface EventSlash {
  /** pool_id is the unique ID of the pool. */
  pool_id: string;
  /** staker is the account address of the protocol node. */
  staker: string;
  /** amount is the total amount that got slashed */
  amount: string;
  /** slash_type is the type of the protocol slash */
  slash_type: SlashType;
  /**
   * stake_fraction is the percentage of how much of the validators total
   * bonded amount was under risk for slashing
   */
  stake_fraction: string;
}

function createBaseEventUpdateParams(): EventUpdateParams {
  return { old_params: undefined, new_params: undefined, payload: "" };
}

export const EventUpdateParams: MessageFns<EventUpdateParams> = {
  encode(message: EventUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.old_params !== undefined) {
      Params.encode(message.old_params, writer.uint32(10).fork()).join();
    }
    if (message.new_params !== undefined) {
      Params.encode(message.new_params, writer.uint32(18).fork()).join();
    }
    if (message.payload !== "") {
      writer.uint32(26).string(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.old_params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.new_params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateParams {
    return {
      old_params: isSet(object.old_params) ? Params.fromJSON(object.old_params) : undefined,
      new_params: isSet(object.new_params) ? Params.fromJSON(object.new_params) : undefined,
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
    };
  },

  toJSON(message: EventUpdateParams): unknown {
    const obj: any = {};
    if (message.old_params !== undefined) {
      obj.old_params = Params.toJSON(message.old_params);
    }
    if (message.new_params !== undefined) {
      obj.new_params = Params.toJSON(message.new_params);
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventUpdateParams>, I>>(base?: I): EventUpdateParams {
    return EventUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventUpdateParams>, I>>(object: I): EventUpdateParams {
    const message = createBaseEventUpdateParams();
    message.old_params = (object.old_params !== undefined && object.old_params !== null)
      ? Params.fromPartial(object.old_params)
      : undefined;
    message.new_params = (object.new_params !== undefined && object.new_params !== null)
      ? Params.fromPartial(object.new_params)
      : undefined;
    message.payload = object.payload ?? "";
    return message;
  },
};

function createBaseEventUpdateCommission(): EventUpdateCommission {
  return { staker: "", pool_id: "0", commission: "" };
}

export const EventUpdateCommission: MessageFns<EventUpdateCommission> = {
  encode(message: EventUpdateCommission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.staker !== "") {
      writer.uint32(10).string(message.staker);
    }
    if (message.pool_id !== "0") {
      writer.uint32(16).uint64(message.pool_id);
    }
    if (message.commission !== "") {
      writer.uint32(26).string(message.commission);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateCommission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateCommission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pool_id = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.commission = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateCommission {
    return {
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
      pool_id: isSet(object.pool_id) ? globalThis.String(object.pool_id) : "0",
      commission: isSet(object.commission) ? globalThis.String(object.commission) : "",
    };
  },

  toJSON(message: EventUpdateCommission): unknown {
    const obj: any = {};
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    if (message.pool_id !== "0") {
      obj.pool_id = message.pool_id;
    }
    if (message.commission !== "") {
      obj.commission = message.commission;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventUpdateCommission>, I>>(base?: I): EventUpdateCommission {
    return EventUpdateCommission.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventUpdateCommission>, I>>(object: I): EventUpdateCommission {
    const message = createBaseEventUpdateCommission();
    message.staker = object.staker ?? "";
    message.pool_id = object.pool_id ?? "0";
    message.commission = object.commission ?? "";
    return message;
  },
};

function createBaseEventUpdateStakeFraction(): EventUpdateStakeFraction {
  return { staker: "", pool_id: "0", stake_fraction: "" };
}

export const EventUpdateStakeFraction: MessageFns<EventUpdateStakeFraction> = {
  encode(message: EventUpdateStakeFraction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.staker !== "") {
      writer.uint32(10).string(message.staker);
    }
    if (message.pool_id !== "0") {
      writer.uint32(16).uint64(message.pool_id);
    }
    if (message.stake_fraction !== "") {
      writer.uint32(26).string(message.stake_fraction);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventUpdateStakeFraction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventUpdateStakeFraction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pool_id = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stake_fraction = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventUpdateStakeFraction {
    return {
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
      pool_id: isSet(object.pool_id) ? globalThis.String(object.pool_id) : "0",
      stake_fraction: isSet(object.stake_fraction) ? globalThis.String(object.stake_fraction) : "",
    };
  },

  toJSON(message: EventUpdateStakeFraction): unknown {
    const obj: any = {};
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    if (message.pool_id !== "0") {
      obj.pool_id = message.pool_id;
    }
    if (message.stake_fraction !== "") {
      obj.stake_fraction = message.stake_fraction;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventUpdateStakeFraction>, I>>(base?: I): EventUpdateStakeFraction {
    return EventUpdateStakeFraction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventUpdateStakeFraction>, I>>(object: I): EventUpdateStakeFraction {
    const message = createBaseEventUpdateStakeFraction();
    message.staker = object.staker ?? "";
    message.pool_id = object.pool_id ?? "0";
    message.stake_fraction = object.stake_fraction ?? "";
    return message;
  },
};

function createBaseEventClaimCommissionRewards(): EventClaimCommissionRewards {
  return { staker: "", amounts: "" };
}

export const EventClaimCommissionRewards: MessageFns<EventClaimCommissionRewards> = {
  encode(message: EventClaimCommissionRewards, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.staker !== "") {
      writer.uint32(10).string(message.staker);
    }
    if (message.amounts !== "") {
      writer.uint32(18).string(message.amounts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventClaimCommissionRewards {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventClaimCommissionRewards();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amounts = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventClaimCommissionRewards {
    return {
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
      amounts: isSet(object.amounts) ? globalThis.String(object.amounts) : "",
    };
  },

  toJSON(message: EventClaimCommissionRewards): unknown {
    const obj: any = {};
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    if (message.amounts !== "") {
      obj.amounts = message.amounts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventClaimCommissionRewards>, I>>(base?: I): EventClaimCommissionRewards {
    return EventClaimCommissionRewards.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventClaimCommissionRewards>, I>>(object: I): EventClaimCommissionRewards {
    const message = createBaseEventClaimCommissionRewards();
    message.staker = object.staker ?? "";
    message.amounts = object.amounts ?? "";
    return message;
  },
};

function createBaseEventJoinPool(): EventJoinPool {
  return { pool_id: "0", staker: "", pool_address: "", amount: "0", commission: "", stake_fraction: "" };
}

export const EventJoinPool: MessageFns<EventJoinPool> = {
  encode(message: EventJoinPool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool_id !== "0") {
      writer.uint32(8).uint64(message.pool_id);
    }
    if (message.staker !== "") {
      writer.uint32(18).string(message.staker);
    }
    if (message.pool_address !== "") {
      writer.uint32(26).string(message.pool_address);
    }
    if (message.amount !== "0") {
      writer.uint32(32).uint64(message.amount);
    }
    if (message.commission !== "") {
      writer.uint32(42).string(message.commission);
    }
    if (message.stake_fraction !== "") {
      writer.uint32(50).string(message.stake_fraction);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventJoinPool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventJoinPool();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pool_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pool_address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.amount = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.commission = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.stake_fraction = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventJoinPool {
    return {
      pool_id: isSet(object.pool_id) ? globalThis.String(object.pool_id) : "0",
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
      pool_address: isSet(object.pool_address) ? globalThis.String(object.pool_address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "0",
      commission: isSet(object.commission) ? globalThis.String(object.commission) : "",
      stake_fraction: isSet(object.stake_fraction) ? globalThis.String(object.stake_fraction) : "",
    };
  },

  toJSON(message: EventJoinPool): unknown {
    const obj: any = {};
    if (message.pool_id !== "0") {
      obj.pool_id = message.pool_id;
    }
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    if (message.pool_address !== "") {
      obj.pool_address = message.pool_address;
    }
    if (message.amount !== "0") {
      obj.amount = message.amount;
    }
    if (message.commission !== "") {
      obj.commission = message.commission;
    }
    if (message.stake_fraction !== "") {
      obj.stake_fraction = message.stake_fraction;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventJoinPool>, I>>(base?: I): EventJoinPool {
    return EventJoinPool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventJoinPool>, I>>(object: I): EventJoinPool {
    const message = createBaseEventJoinPool();
    message.pool_id = object.pool_id ?? "0";
    message.staker = object.staker ?? "";
    message.pool_address = object.pool_address ?? "";
    message.amount = object.amount ?? "0";
    message.commission = object.commission ?? "";
    message.stake_fraction = object.stake_fraction ?? "";
    return message;
  },
};

function createBaseEventLeavePool(): EventLeavePool {
  return { pool_id: "0", staker: "" };
}

export const EventLeavePool: MessageFns<EventLeavePool> = {
  encode(message: EventLeavePool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool_id !== "0") {
      writer.uint32(8).uint64(message.pool_id);
    }
    if (message.staker !== "") {
      writer.uint32(18).string(message.staker);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventLeavePool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventLeavePool();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pool_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventLeavePool {
    return {
      pool_id: isSet(object.pool_id) ? globalThis.String(object.pool_id) : "0",
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
    };
  },

  toJSON(message: EventLeavePool): unknown {
    const obj: any = {};
    if (message.pool_id !== "0") {
      obj.pool_id = message.pool_id;
    }
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventLeavePool>, I>>(base?: I): EventLeavePool {
    return EventLeavePool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventLeavePool>, I>>(object: I): EventLeavePool {
    const message = createBaseEventLeavePool();
    message.pool_id = object.pool_id ?? "0";
    message.staker = object.staker ?? "";
    return message;
  },
};

function createBaseEventSlash(): EventSlash {
  return { pool_id: "0", staker: "", amount: "0", slash_type: SlashType.SLASH_TYPE_UNSPECIFIED, stake_fraction: "" };
}

export const EventSlash: MessageFns<EventSlash> = {
  encode(message: EventSlash, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool_id !== "0") {
      writer.uint32(8).uint64(message.pool_id);
    }
    if (message.staker !== "") {
      writer.uint32(18).string(message.staker);
    }
    if (message.amount !== "0") {
      writer.uint32(24).uint64(message.amount);
    }
    if (message.slash_type !== SlashType.SLASH_TYPE_UNSPECIFIED) {
      writer.uint32(32).int32(slashTypeToNumber(message.slash_type));
    }
    if (message.stake_fraction !== "") {
      writer.uint32(42).string(message.stake_fraction);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventSlash {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventSlash();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pool_id = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.staker = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.amount = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.slash_type = slashTypeFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.stake_fraction = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventSlash {
    return {
      pool_id: isSet(object.pool_id) ? globalThis.String(object.pool_id) : "0",
      staker: isSet(object.staker) ? globalThis.String(object.staker) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "0",
      slash_type: isSet(object.slash_type) ? slashTypeFromJSON(object.slash_type) : SlashType.SLASH_TYPE_UNSPECIFIED,
      stake_fraction: isSet(object.stake_fraction) ? globalThis.String(object.stake_fraction) : "",
    };
  },

  toJSON(message: EventSlash): unknown {
    const obj: any = {};
    if (message.pool_id !== "0") {
      obj.pool_id = message.pool_id;
    }
    if (message.staker !== "") {
      obj.staker = message.staker;
    }
    if (message.amount !== "0") {
      obj.amount = message.amount;
    }
    if (message.slash_type !== SlashType.SLASH_TYPE_UNSPECIFIED) {
      obj.slash_type = slashTypeToJSON(message.slash_type);
    }
    if (message.stake_fraction !== "") {
      obj.stake_fraction = message.stake_fraction;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventSlash>, I>>(base?: I): EventSlash {
    return EventSlash.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventSlash>, I>>(object: I): EventSlash {
    const message = createBaseEventSlash();
    message.pool_id = object.pool_id ?? "0";
    message.staker = object.staker ?? "";
    message.amount = object.amount ?? "0";
    message.slash_type = object.slash_type ?? SlashType.SLASH_TYPE_UNSPECIFIED;
    message.stake_fraction = object.stake_fraction ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
