name: Build binaries check

on:
  workflow_call:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: install yarn
        run: npm install --global yarn
      - name: "setup"
        run: yarn setup
      - name: "build:binaries"
        working-directory: .
        run: yarn build:binaries
