name: lint checks

on:
  - pull_request

jobs:
  yarn-lint:
    runs-on: ubuntu-latest
    env:
      npm_config_user: "root"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "nodejs install"
        uses: actions/setup-node@v3
      - name: install yarn
        run: npm install --global yarn
      - name: "setup"
        run: yarn setup
      - name: "lint"
        run: yarn lint

  golangci:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4
      # Setup Golang
      - name: 🐿 Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: 'e2etest/go.mod'
      # Lint e2etest with golangci-lint
      - name: Lint e2etest with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
          working-directory: e2etest
      # Lint kystrap with golangci-lint
      - name: Lint kystrap with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
          working-directory: tools/kystrap
